config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
    resources :posts
    resources :categories

   root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	#attr_accessible :name (attr_accessible IS NO LONGER USED IN RAILS 4+)
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessible :title, :body, :category_id, :author_id (attr_accessible IS NO LONGER USED IN RAILS 4+)
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.find(params[:id])
    @title = @category.name
    @posts = @category.post
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all
	end

	def new
		@post = Post.new
		@category = Category.all

	end

	def create
		@post = Post.new{params[:post]}
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved"
		else
			render "new"
		end
	end

	def edit
		@post = Post.find{params[:id]}
	end

	def update
		@post = Post.find{params[:id]}

		if @post.update_attributes{params[:post]}
			redirect_to post_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
	end

	def show
		@post = Post.find{params[:id]}

	end

	def destroy
		@post = Post.find{params[:id]}
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>
<ul>
  <li><% @categories.each do |category| %></li>
  <li><%= link_to category.name, category %></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @posts.each do |post| %>
	<h3><%= link_to post.title, post %> </h3>
	<p><%= post.body %>
<% end.empty y? %>
	<p>Sorry, there are no posts in this category</p>
<% end %>
<%= link_to "Back to Categories", categories.path %>

app/views/home/index.html.erb
<h1>This is my Ruby Blog</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key,value| %>
	<p><%= value %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @post.each do |post| %>
	<h3><%= link_to post.title, post %></h3>
	<p><%= post.body %></p>
	<!--hr tag is used to define a thematic change in the content-->
	<hr>
<% end %>
<%= link_to "Add new post", new_post_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d %Y") %></small>
<p><%= @post.body %></p>
<p>Category: <%= @post.category.name, category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back", posts_path %></p>